services:
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-website
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.portfolio.rule: "Host(`adamlin.online`) || Host(`www.adamlin.online`)"
      traefik.http.routers.portfolio.entrypoints: "web,websecure"
      traefik.http.routers.portfolio.tls: "true"
      traefik.http.routers.portfolio.tls.certresolver: "letsencrypt"
      traefik.http.services.portfolio.loadbalancer.server.port: "3000"
